# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RailLineDetectionTool
                                 A QGIS plugin
 this plugine used to detect distance between 2 line if distance less than 3 martk the error point
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-02-21
        copyright            : (C) 2023 by genesys
        email                : pramoddb@email.igenesys.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RailLineDetectionTool class from file RailLineDetectionTool.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .rail_line_detection_tool import RailLineDetectionTool
    return RailLineDetectionTool(iface)
