# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PTPTools
                                 A QGIS plugin
 Tools For PTP
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-03-08
        copyright            : (C) 2021 by Sibin Sarmadan
        email                : sibinsa@email.igenesys.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Sibin Sarmadan'
__date__ = '2021-03-08'
__copyright__ = '(C) 2021 by Sibin Sarmadan'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PTPTools class from file PTPTools.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .PTPTools import PTPToolsPlugin
    return PTPToolsPlugin()
