# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TransitionsDialog
                                 A QGIS plugin
 Creation of transition
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-10-21
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Pramod
        email                : pramoddb@email.igenesys.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'transition_dialog_base.ui'))


class TransitionsDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, tool,parent=None):
        """Constructor."""
        super(TransitionsDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        self.tool = tool

    def closeEvent(self, QCloseEvent):
        # print('ghm',self.tool.layer)
        # try:
        self.tool.layer.selectionChanged.disconnect(self.tool.getSelectedFeatures)
        # except:
        #     pass
        # pass
