# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ParellelOffset
                                 A QGIS plugin
 This Plugin offset line feature 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-03-23
        copyright            : (C) 2023 by Shubham Udiwal
        email                : shubhamud@email.igenesys.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ParellelOffset class from file ParellelOffset.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .parellel_offset import ParellelOffset
    return ParellelOffset(iface)
