# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Qccheckerril
                                 A QGIS plugin
 qc checker for ril 2d bulding and maek error point
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-05-12
        copyright            : (C) 2023 by genesys
        email                : pramoddb@email.igenesys.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Qccheckerril class from file Qccheckerril.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .qc_checker_ril_2d import Qccheckerril
    return Qccheckerril(iface)
