# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MoveTolForRIL
                                 A QGIS plugin
 moveing geometry and add gen remark moved for genesys
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-04-17
        copyright            : (C) 2023 by genesys
        email                : "Pramod Bahir" <pramoddb@email.igenesys.com>; 
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MoveTolForRIL class from file MoveTolForRIL.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .move_tool import MoveTolForRIL
    return MoveTolForRIL(iface)
