# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Topologychecker
                                 A QGIS plugin
 Performs topology checks
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-03-15
        copyright            : (C) 2021 by TopologyChecKer
        email                : TopologyChecKer
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Topologychecker class from file Topologychecker.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from . TopologyChecker import Topologychecker
    return Topologychecker(iface)
